# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

# This should be run after running
# flutter build apk --release
# to build the app using the Flutter toolchain.
platform :android do
  desc 'Push the built release APK to alpha or beta depending on current branch'
  lane :deploy_play_store do
    begin
      upload_to_play_store(
        track: 'alpha',
        apk: '../build/app/outputs/apk/release/app-release.apk',
        json_key_data: ENV['GOOGLE_DEVELOPER_SERVICE_ACCOUNT_ACTOR_FASTLANE'],
        skip_upload_screenshots: true,
        skip_upload_images: true
      )
    rescue => exception
      raise exception unless exception.message.include?('apkUpgradeVersionConflict')
      puts 'Current version already present on the Play Store. Omitting this upload.'
    end
  end
end
